# Generated by Django 5.1.4 on 2024-12-28 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomEmp', models.CharField(max_length=50)),
                ('PrenomEmp', models.CharField(max_length=50)),
                ('Date_nais_Emp', models.DateField()),
                ('Date_Rec', models.DateField()),
                ('AdressEmp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomFormation', models.CharField(max_length=50)),
                ('DateDebFor', models.DateField()),
                ('DateFinFor', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HR_Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_HR_manager', models.CharField(max_length=50)),
                ('Prenom_HR_manager', models.CharField(max_length=50)),
                ('Email_HR_manager', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeContrat', models.CharField(max_length=50)),
                ('Date_deb_cnt', models.DateField()),
                ('Date_fin_cnt', models.DateField()),
                ('salaireMenseul', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Employe_cnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_deb', models.DateField()),
                ('Date_fin', models.DateField()),
                ('TypeConge', models.CharField(max_length=50)),
                ('SatutCng', models.CharField(max_length=50)),
                ('Employe_conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Participer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_participation', models.DateField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.employe')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.formation')),
            ],
        ),
        migrations.AddField(
            model_name='formation',
            name='Employes_for',
            field=models.ManyToManyField(through='projet_app.Participer', to='projet_app.employe'),
        ),
        migrations.CreateModel(
            name='Recrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateRec', models.DateField()),
                ('Poste', models.CharField(max_length=50)),
                ('StatutRec', models.CharField(max_length=50)),
                ('Employe_recruter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mois', models.CharField(max_length=50)),
                ('annee', models.IntegerField()),
                ('Montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statutSalaire', models.CharField(max_length=50)),
                ('Employe_sal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_service', models.CharField(max_length=50)),
                ('description_ser', models.CharField(max_length=50)),
                ('hr_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.hr_manager')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='Employes_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_app.service'),
        ),
    ]
